name: ofx_parser
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  xml2json: ^5.3.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
